substitutions:
  devicename: e32c-sa2023-1
  hass_api_name: "esp32_cam_sa1"
  my_ip: 192.168.1.101
  my_gateway: 192.168.1.1
  my_subnet: 255.255.255.0
  mytopic: esp32camsleep/esp32cam-sa1
  my_topic_prefix: esp32camsleep
  my_otatopic: esp32camsleep/ota_mode
  runduration: 2min
  sleepduration: 60min
  my_payload: 'online2023'
  swname: 'homegrow-csc.pm2kbis-cam'
  wifi_ssid: "SSID"
  wifi_pass: "PSK"

<<: !include esp32cam-core.yaml
